Test build

diff --git a/.github/workflows/build-cli.yml b/.github/workflows/build-cli.yml
--- a/.github/workflows/build-cli.yml
+++ b/.github/workflows/build-cli.yml
@@ -87,6 +87,10 @@ jobs:
           echo "SHORT_RUNNER_OS=$(echo $RUNNER_OS | awk '{print substr($0, 1, 3)}' | \
             awk '{print tolower($0)}')" >> $GITHUB_ENV
 
+      - name: Configure binfmt with QEMU User Emulation
+        run: |
+          apt install qemu binfmt-support qemu-user-static
+
       - name: Set up Node
         uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048  # v3.2.0
         with:
@@ -106,41 +110,41 @@ jobs:
       - name: Build & Package Unix
         run: npm run dist:${{ env.SHORT_RUNNER_OS }} --quiet
 
-      - name: Zip Unix
-        run: |
-          cd ./dist/${{ env.LOWER_RUNNER_OS }}
-          zip ../bw-${{ env.LOWER_RUNNER_OS }}-${{ env._PACKAGE_VERSION }}.zip ./bw
+      # - name: Zip Unix
+      #   run: |
+      #     cd ./dist/${{ env.LOWER_RUNNER_OS }}
+      #     zip ../bw-${{ env.LOWER_RUNNER_OS }}-${{ env._PACKAGE_VERSION }}.zip ./bw
 
-      - name: Version Test
-        run: |
-          unzip "./dist/bw-${{ env.LOWER_RUNNER_OS }}-${{ env._PACKAGE_VERSION }}.zip" -d "./test"
-          testVersion=$(./test/bw -v)
-          echo "version: $_PACKAGE_VERSION"
-          echo "testVersion: $testVersion"
-          if [[ $testVersion != $_PACKAGE_VERSION ]]; then
-            echo "Version test failed."
-            exit 1
-          fi
+      # - name: Version Test
+      #   run: |
+      #     unzip "./dist/bw-${{ env.LOWER_RUNNER_OS }}-${{ env._PACKAGE_VERSION }}.zip" -d "./test"
+      #     testVersion=$(./test/bw -v)
+      #     echo "version: $_PACKAGE_VERSION"
+      #     echo "testVersion: $testVersion"
+      #     if [[ $testVersion != $_PACKAGE_VERSION ]]; then
+      #       echo "Version test failed."
+      #       exit 1
+      #     fi
 
-      - name: Create checksums Unix
-        run: |
-          cd ./dist
-          shasum -a 256 bw-${{ env.LOWER_RUNNER_OS }}-${{ env._PACKAGE_VERSION }}.zip \
-            | awk '{split($0, a); print a[1]}' > bw-${{ env.LOWER_RUNNER_OS }}-sha256-${{ env._PACKAGE_VERSION }}.txt
+      # - name: Create checksums Unix
+      #   run: |
+      #     cd ./dist
+      #     shasum -a 256 bw-${{ env.LOWER_RUNNER_OS }}-${{ env._PACKAGE_VERSION }}.zip \
+      #       | awk '{split($0, a); print a[1]}' > bw-${{ env.LOWER_RUNNER_OS }}-sha256-${{ env._PACKAGE_VERSION }}.txt
 
-      - name: Upload unix zip asset
-        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
-        with:
-          name: bw-${{ env.LOWER_RUNNER_OS }}-${{ env._PACKAGE_VERSION }}.zip
-          path: apps/cli/dist/bw-${{ env.LOWER_RUNNER_OS }}-${{ env._PACKAGE_VERSION }}.zip
-          if-no-files-found: error
+      # - name: Upload unix zip asset
+      #   uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
+      #   with:
+      #     name: bw-${{ env.LOWER_RUNNER_OS }}-${{ env._PACKAGE_VERSION }}.zip
+      #     path: apps/cli/dist/bw-${{ env.LOWER_RUNNER_OS }}-${{ env._PACKAGE_VERSION }}.zip
+      #     if-no-files-found: error
 
-      - name: Upload unix checksum asset
-        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
-        with:
-          name: bw-${{ env.LOWER_RUNNER_OS }}-sha256-${{ env._PACKAGE_VERSION }}.txt
-          path: apps/cli/dist/bw-${{ env.LOWER_RUNNER_OS }}-sha256-${{ env._PACKAGE_VERSION }}.txt
-          if-no-files-found: error
+      # - name: Upload unix checksum asset
+      #   uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
+      #   with:
+      #     name: bw-${{ env.LOWER_RUNNER_OS }}-sha256-${{ env._PACKAGE_VERSION }}.txt
+      #     path: apps/cli/dist/bw-${{ env.LOWER_RUNNER_OS }}-sha256-${{ env._PACKAGE_VERSION }}.txt
+      #     if-no-files-found: error
 
   cli-windows:
     name: Build CLI Windows
@@ -235,131 +239,131 @@ jobs:
       - name: Build & Package Windows
         run: npm run dist:win --quiet
 
-      - name: Package Chocolatey
-        shell: pwsh
-        run: |
-          Copy-Item -Path stores/chocolatey -Destination dist/chocolatey -Recurse
-          Copy-Item dist/windows/bw.exe -Destination dist/chocolatey/tools
-          Copy-Item ${{ github.workspace }}/LICENSE.txt -Destination dist/chocolatey/tools
-          choco pack dist/chocolatey/bitwarden-cli.nuspec --version ${{ env._PACKAGE_VERSION }} --out dist/chocolatey
+      # - name: Package Chocolatey
+      #   shell: pwsh
+      #   run: |
+      #     Copy-Item -Path stores/chocolatey -Destination dist/chocolatey -Recurse
+      #     Copy-Item dist/windows/bw.exe -Destination dist/chocolatey/tools
+      #     Copy-Item ${{ github.workspace }}/LICENSE.txt -Destination dist/chocolatey/tools
+      #     choco pack dist/chocolatey/bitwarden-cli.nuspec --version ${{ env._PACKAGE_VERSION }} --out dist/chocolatey
 
-      - name: Zip Windows
-        shell: cmd
-        run: 7z a ./dist/bw-windows-%_PACKAGE_VERSION%.zip ./dist/windows/bw.exe
+      # - name: Zip Windows
+      #   shell: cmd
+      #   run: 7z a ./dist/bw-windows-%_PACKAGE_VERSION%.zip ./dist/windows/bw.exe
 
-      - name: Version Test
-        run: |
-          dir ./dist/
-          Expand-Archive -Path "./dist/bw-windows-${env:_PACKAGE_VERSION}.zip" -DestinationPath "./test/windows"
-          $testVersion = Invoke-Expression '& ./test/windows/bw.exe -v'
-          echo "version: $env:_PACKAGE_VERSION"
-          echo "testVersion: $testVersion"
-          if($testVersion -ne $env:_PACKAGE_VERSION) {
-            Throw "Version test failed."
-          }
+      # - name: Version Test
+      #   run: |
+      #     dir ./dist/
+      #     Expand-Archive -Path "./dist/bw-windows-${env:_PACKAGE_VERSION}.zip" -DestinationPath "./test/windows"
+      #     $testVersion = Invoke-Expression '& ./test/windows/bw.exe -v'
+      #     echo "version: $env:_PACKAGE_VERSION"
+      #     echo "testVersion: $testVersion"
+      #     if($testVersion -ne $env:_PACKAGE_VERSION) {
+      #       Throw "Version test failed."
+      #     }
 
-      - name: Create checksums Windows
-        run: |
-          checksum -f="./dist/bw-windows-${env:_PACKAGE_VERSION}.zip" `
-            -t sha256 | Out-File -Encoding ASCII ./dist/bw-windows-sha256-${env:_PACKAGE_VERSION}.txt
+      # - name: Create checksums Windows
+      #   run: |
+      #     checksum -f="./dist/bw-windows-${env:_PACKAGE_VERSION}.zip" `
+      #       -t sha256 | Out-File -Encoding ASCII ./dist/bw-windows-sha256-${env:_PACKAGE_VERSION}.txt
 
-      - name: Upload windows zip asset
-        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
-        with:
-          name: bw-windows-${{ env._PACKAGE_VERSION }}.zip
-          path: apps/cli/dist/bw-windows-${{ env._PACKAGE_VERSION }}.zip
-          if-no-files-found: error
+      # - name: Upload windows zip asset
+      #   uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
+      #   with:
+      #     name: bw-windows-${{ env._PACKAGE_VERSION }}.zip
+      #     path: apps/cli/dist/bw-windows-${{ env._PACKAGE_VERSION }}.zip
+      #     if-no-files-found: error
 
-      - name: Upload windows checksum asset
-        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
-        with:
-          name: bw-windows-sha256-${{ env._PACKAGE_VERSION }}.txt
-          path: apps/cli/dist/bw-windows-sha256-${{ env._PACKAGE_VERSION }}.txt
-          if-no-files-found: error
+      # - name: Upload windows checksum asset
+      #   uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
+      #   with:
+      #     name: bw-windows-sha256-${{ env._PACKAGE_VERSION }}.txt
+      #     path: apps/cli/dist/bw-windows-sha256-${{ env._PACKAGE_VERSION }}.txt
+      #     if-no-files-found: error
 
-      - name: Upload Chocolatey asset
-        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
-        with:
-          name: bitwarden-cli.${{ env._PACKAGE_VERSION }}.nupkg
-          path: apps/cli/dist/chocolatey/bitwarden-cli.${{ env._PACKAGE_VERSION }}.nupkg
-          if-no-files-found: error
+      # - name: Upload Chocolatey asset
+      #   uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
+      #   with:
+      #     name: bitwarden-cli.${{ env._PACKAGE_VERSION }}.nupkg
+      #     path: apps/cli/dist/chocolatey/bitwarden-cli.${{ env._PACKAGE_VERSION }}.nupkg
+      #     if-no-files-found: error
 
-      - name: Upload NPM Build Directory asset
-        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
-        with:
-          name: bitwarden-cli-${{ env._PACKAGE_VERSION }}-npm-build.zip
-          path: apps/cli/build
-          if-no-files-found: error
+      # - name: Upload NPM Build Directory asset
+      #   uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
+      #   with:
+      #     name: bitwarden-cli-${{ env._PACKAGE_VERSION }}-npm-build.zip
+      #     path: apps/cli/build
+      #     if-no-files-found: error
 
-  snap:
-    name: Build Snap
-    runs-on: ubuntu-20.04
-    needs: [setup, cli]
-    env:
-      _PACKAGE_VERSION: ${{ needs.setup.outputs.package_version }}
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3.0.2
+  # snap:
+  #   name: Build Snap
+  #   runs-on: ubuntu-20.04
+  #   needs: [setup, cli]
+  #   env:
+  #     _PACKAGE_VERSION: ${{ needs.setup.outputs.package_version }}
+  #   steps:
+  #     - name: Checkout repo
+  #       uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3.0.2
 
-      - name: Print environment
-        run: |
-          whoami
-          echo "GitHub ref: $GITHUB_REF"
-          echo "GitHub event: $GITHUB_EVENT"
-          echo "BW Package Version: $_PACKAGE_VERSION"
+  #     - name: Print environment
+  #       run: |
+  #         whoami
+  #         echo "GitHub ref: $GITHUB_REF"
+  #         echo "GitHub event: $GITHUB_EVENT"
+  #         echo "BW Package Version: $_PACKAGE_VERSION"
 
-      - name: Get bw linux cli
-        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
-        with:
-          name: bw-linux-${{ env._PACKAGE_VERSION }}.zip
-          path: apps/cli/dist/snap
+  #     - name: Get bw linux cli
+  #       uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
+  #       with:
+  #         name: bw-linux-${{ env._PACKAGE_VERSION }}.zip
+  #         path: apps/cli/dist/snap
 
-      - name: Setup Snap Package
-        run: |
-          cp -r stores/snap/* -t dist/snap
-          sed -i s/__version__/${{ env._PACKAGE_VERSION }}/g dist/snap/snapcraft.yaml
-          cd dist/snap
-          ls -alth
+  #     - name: Setup Snap Package
+  #       run: |
+  #         cp -r stores/snap/* -t dist/snap
+  #         sed -i s/__version__/${{ env._PACKAGE_VERSION }}/g dist/snap/snapcraft.yaml
+  #         cd dist/snap
+  #         ls -alth
 
-      - name: Build snap
-        uses: snapcore/action-build@ea14cdeb353272f75977040488ca191880509a8c  # v1.1.0
-        with:
-          path: apps/cli/dist/snap
+  #     - name: Build snap
+  #       uses: snapcore/action-build@ea14cdeb353272f75977040488ca191880509a8c  # v1.1.0
+  #       with:
+  #         path: apps/cli/dist/snap
 
-      - name: Create checksum
-        run: |
-          cd dist/snap
-          ls -alth
-          sha256sum bw_${{ env._PACKAGE_VERSION }}_amd64.snap \
-            | awk '{split($0, a); print a[1]}' > bw-snap-sha256-${{ env._PACKAGE_VERSION }}.txt
+  #     - name: Create checksum
+  #       run: |
+  #         cd dist/snap
+  #         ls -alth
+  #         sha256sum bw_${{ env._PACKAGE_VERSION }}_amd64.snap \
+  #           | awk '{split($0, a); print a[1]}' > bw-snap-sha256-${{ env._PACKAGE_VERSION }}.txt
 
-      - name: Install Snap
-        run: sudo snap install dist/snap/bw*.snap --dangerous
+  #     - name: Install Snap
+  #       run: sudo snap install dist/snap/bw*.snap --dangerous
 
-      - name: Test Snap
-        shell: pwsh
-        run: |
-          $testVersion = Invoke-Expression '& bw -v'
-          if($testVersion -ne $env:_PACKAGE_VERSION) {
-            Throw "Version test failed."
-          }
-        env:
-          BITWARDENCLI_APPDATA_DIR: "/home/runner/snap/bw/x1/.config/Bitwarden CLI"
+  #     - name: Test Snap
+  #       shell: pwsh
+  #       run: |
+  #         $testVersion = Invoke-Expression '& bw -v'
+  #         if($testVersion -ne $env:_PACKAGE_VERSION) {
+  #           Throw "Version test failed."
+  #         }
+  #       env:
+  #         BITWARDENCLI_APPDATA_DIR: "/home/runner/snap/bw/x1/.config/Bitwarden CLI"
 
-      - name: Cleanup Test & Update Snap for Publish
-        shell: pwsh
-        run: sudo snap remove bw
+  #     - name: Cleanup Test & Update Snap for Publish
+  #       shell: pwsh
+  #       run: sudo snap remove bw
 
-      - name: Upload snap asset
-        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
-        with:
-          name: bw_${{ env._PACKAGE_VERSION }}_amd64.snap
-          path: apps/cli/dist/snap/bw_${{ env._PACKAGE_VERSION }}_amd64.snap
-          if-no-files-found: error
+  #     - name: Upload snap asset
+  #       uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
+  #       with:
+  #         name: bw_${{ env._PACKAGE_VERSION }}_amd64.snap
+  #         path: apps/cli/dist/snap/bw_${{ env._PACKAGE_VERSION }}_amd64.snap
+  #         if-no-files-found: error
 
-      - name: Upload snap checksum asset
-        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
-        with:
-          name: bw-snap-sha256-${{ env._PACKAGE_VERSION }}.txt
-          path: apps/cli/dist/snap/bw-snap-sha256-${{ env._PACKAGE_VERSION }}.txt
-          if-no-files-found: error
+  #     - name: Upload snap checksum asset
+  #       uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
+  #       with:
+  #         name: bw-snap-sha256-${{ env._PACKAGE_VERSION }}.txt
+  #         path: apps/cli/dist/snap/bw-snap-sha256-${{ env._PACKAGE_VERSION }}.txt
+  #         if-no-files-found: error
