Build arch individually for each os

diff --git a/.github/workflows/build-cli.yml b/.github/workflows/build-cli.yml
--- a/.github/workflows/build-cli.yml
+++ b/.github/workflows/build-cli.yml
@@ -69,7 +69,8 @@ jobs:
     name: Build CLI ${{ matrix.os }}
     strategy:
       matrix:
-        os: [lin, mac, win]
+        arch: [x64, arm64]
+        os: [linux, macos, windows]
     runs-on: ubuntu-20.04
     needs:
       - setup
@@ -81,7 +82,6 @@ jobs:
 
       - name: Setup Unix Vars
         run: |
-          echo "LOWER_RUNNER_OS=$(echo $RUNNER_OS | awk '{print tolower($0)}')" >> $GITHUB_ENV
           echo "SHORT_RUNNER_OS=$(echo $RUNNER_OS | awk '{print substr($0, 1, 3)}' | \
             awk '{print tolower($0)}')" >> $GITHUB_ENV
 
@@ -106,43 +106,43 @@ jobs:
         working-directory: ./
 
       - name: Build & Package Unix
-        run: npm run dist:${{ matrix.os }} --quiet
+        run: npm run dist:${{ matrix.os }}:${{ matrix.arch }} --quiet
 
-      # - name: Zip Unix
-      #   run: |
-      #     cd ./dist/${{ env.LOWER_RUNNER_OS }}
-      #     zip ../bw-${{ env.LOWER_RUNNER_OS }}-${{ env._PACKAGE_VERSION }}.zip ./bw
+      - name: Zip Unix
+        run: |
+          cd ./dist/${{ matrix.os }}/${{ matrix.arch }}
+          zip ../bw-${{ matrix.os }}-${{ env._PACKAGE_VERSION }}-${{ matrix.arch }}.zip ./bw
 
-      # - name: Version Test
-      #   run: |
-      #     unzip "./dist/bw-${{ env.LOWER_RUNNER_OS }}-${{ env._PACKAGE_VERSION }}.zip" -d "./test"
-      #     testVersion=$(./test/bw -v)
-      #     echo "version: $_PACKAGE_VERSION"
-      #     echo "testVersion: $testVersion"
-      #     if [[ $testVersion != $_PACKAGE_VERSION ]]; then
-      #       echo "Version test failed."
-      #       exit 1
-      #     fi
+      - name: Version Test
+        run: |
+          unzip "./dist/bw-${{ matrix.os }}-${{ env._PACKAGE_VERSION }}-${{ matrix.arch }}.zip" -d "./test"
+          testVersion=$(./test/bw -v)
+          echo "version: $_PACKAGE_VERSION"
+          echo "testVersion: $testVersion"
+          if [[ $testVersion != $_PACKAGE_VERSION ]]; then
+            echo "Version test failed."
+            exit 1
+          fi
 
-      # - name: Create checksums Unix
-      #   run: |
-      #     cd ./dist
-      #     shasum -a 256 bw-${{ env.LOWER_RUNNER_OS }}-${{ env._PACKAGE_VERSION }}.zip \
-      #       | awk '{split($0, a); print a[1]}' > bw-${{ env.LOWER_RUNNER_OS }}-sha256-${{ env._PACKAGE_VERSION }}.txt
+      - name: Create checksums Unix
+        run: |
+          cd ./dist
+          shasum -a 256 bw-${{ matrix.os }}-${{ env._PACKAGE_VERSION }}-${{ matrix.arch }}.zip \
+            | awk '{split($0, a); print a[1]}' > bw-${{ matrix.os }}-sha256-${{ env._PACKAGE_VERSION }}-${{ matrix.arch }}.txt
 
-      # - name: Upload unix zip asset
-      #   uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
-      #   with:
-      #     name: bw-${{ env.LOWER_RUNNER_OS }}-${{ env._PACKAGE_VERSION }}.zip
-      #     path: apps/cli/dist/bw-${{ env.LOWER_RUNNER_OS }}-${{ env._PACKAGE_VERSION }}.zip
-      #     if-no-files-found: error
+      - name: Upload unix zip asset
+        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
+        with:
+          name: bw-${{ matrix.os }}-${{ env._PACKAGE_VERSION }}-${{ matrix.arch }}.zip
+          path: apps/cli/dist/bw-${{ matrix.os }}-${{ env._PACKAGE_VERSION }}-${{ matrix.arch }}.zip
+          if-no-files-found: error
 
-      # - name: Upload unix checksum asset
-      #   uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
-      #   with:
-      #     name: bw-${{ env.LOWER_RUNNER_OS }}-sha256-${{ env._PACKAGE_VERSION }}.txt
-      #     path: apps/cli/dist/bw-${{ env.LOWER_RUNNER_OS }}-sha256-${{ env._PACKAGE_VERSION }}.txt
-      #     if-no-files-found: error
+      - name: Upload unix checksum asset
+        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
+        with:
+          name: bw-${{ matrix.os }}-sha256-${{ env._PACKAGE_VERSION }}-${{ matrix.arch }}.txt
+          path: apps/cli/dist/bw-${{ matrix.os }}-sha256-${{ env._PACKAGE_VERSION }}-${{ matrix.arch }}.txt
+          if-no-files-found: error
 
   # cli-windows:
   #   name: Build CLI Windows
